export const FETCH_TASK = "FETCH_TASK"
export const FETCH_TASK_SUCCESS = "FETCH_TASK_SUCCESS"
export const FETCH_TASK_FALSE = "FETCH_TASK_FALSE"

export const FILTER_TASK = "FILTER_TASK"
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS"

export const ADD_TASK = "ADD_TASK"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FALSE = "ADD_TASK_FALSE"

export const TASK_EDITING = "TASK_EDITING"

export const UPDATE_TASK = "UPDATE_TASK"
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FALSE = "UPDATE_TASK_FALSE"